### ISSUE TITLE
Logo 

### ISSUE THREAD

**Issue by AndreVarandas** [AndreVarandas/memoria-leonina#2]
Feature request:

We need a cool logo to use on our project readme, favicon and main page.

**Comment by Guillergood** [comment]
I can help with this. Any idea in mind?

**Comment by Guillergood** [comment]
I think I have a logo, based on your description. Let me know if you like it 😄 
![Logo Memória Leonina](https://github.com/AndreVarandas/memoria-leonina/assets/16701917/e0355eef-2ac6-47a4-813e-24cc97d9c5d4)

It combines the lion and the colors of the Sporting Clube de Portugal (White, dark yellow and green).

**Comment by AndreVarandas** [comment]
Hi @Guillergood thanks for your help, it looks great! 

Do you want to include it in the header of the readme.md file? You could just the new logo to the `public` folder and then just reference it as:

`![Memoria Leonina Logo](public/logo.png)`

**Comment by Guillergood** [comment]
Done, the PR is open and linked to this issue 😄
